### ISSUE TITLE
ImportError: No module named 'markdown'

### ISSUE THREAD

**Issue by stephane84** [jpfleury/gedit-markdown#4]
Just after installing this extension with ./gedit-markdown.sh install, I opened gedit and the highlighting was working, but when activating the plugin in the preferences, I got a red icon "forbidden sign" with the following error in console :

    Traceback (most recent call last):
      File "/home/stephane/.local/share/gedit/plugins/markdown-preview/__init__.py", line 25, in <module>
        import markdown
    ImportError: No module named 'markdown'
    
    (gedit:5668): libpeas-WARNING **: Error loading plugin 'markdown-preview'

It seems that I'm trying to activiate a non-existing plugin :-(

Ubuntu 14.04, with gedit 3.10.4
ps : je suis francophone, donc on peut continuer en français.... ;-)

**Comment by rlafuente** [comment]
I had this problem too on Debian Testing. `apt-get install python3-markdown` fixed it for me, but I was only able to figure it by launching Gedit in a terminal and looking at the error. Maybe indicate this step after the installation script ends?

**Comment by jpfleury** [comment]
@rlafuente: actually, it's written in the [Requirements](https://github.com/jpfleury/gedit-markdown#requirements) section of the README file.

**Comment by rlafuente** [comment]
Oof, my bad! Sorry for the noise.

**Comment by jpfleury** [comment]
No problem. :)

**Comment by akanshajainn** [comment]
https://stackoverflow.com/a/51039940/8708311
